#!groovy

pipeline {
    agent {
        node {
            label 'recommendations-service-1b'
        }
    }
    options {
        timeout(time: 1, unit: 'HOURS')
        timestamps ()
    }
    parameters {
        string(name: 'USERNAME', description: 'username (optional)')
        string(name: 'PASSWORD', description: 'password (optional)')
        gitParameter (name: 'BRANCH', type: 'PT_BRANCH', useRepository: '.*cypress-mochawesome-docker.git', quickFilterEnabled: true, defaultValue: 'master', selectedValue: 'DEFAULT', branchFilter: 'origin/(.*)')
    }
    stages {
        stage('Git checkout') {
            steps {
                git branch: "${params.BRANCH}",
                    url: 'git@github.com:eliran-shani/cypress-mochawesome-docker.git'
            }
        }
        stage('Set display name') {
            steps {
                script {
                    currentBuild.displayName = "${params.BRANCH}"
                }
            }
        }
        stage('Build Docker & Run tests') {
            steps {
                script {

                    // Default credentials (if none provided)
                    if ("${params.USERNAME}" == '' | "${params.PASSWORD}" == '') {
                        load "${JENKINS_HOME}/.envvars/envvars.groovy"
                        sh "./scripts/docker/run_and_record_sanity_tests.bash ${env.USERNAME} ${env.PASSWORD}"
                    }

                    // Ad-hoc credentials
                    else {
                        sh "./scripts/docker/run_and_record_sanity_tests.bash ${params.USERNAME} ${params.PASSWORD}"
                    }
                }
            }
        }
    }
}
